repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: double-quote-string-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
